src/app/core/components/questions/add-question-form/add-question-form.component.html, src/app/core/components/questions/add-question-form/add-question-form.component.scss, src/app/core/components/questions/add-question-form/add-question-form.component.ts
Add inform when question added
=> Add correct input on question. Add info when question added

src/app/app-routing.module.ts, src/app/core/components/lessons/lessons.module.ts, src/app/core/components/lessons/my-passed-test/my-passed-test.component.html, src/app/core/components/lessons/my-passed-test/my-passed-test.component.ts, src/app/core/interface/test.interface.ts, src/app/core/services/user/user.service.ts, src/app/shared/components/header/header.component.html
Create functional  to get  result passed tests
=> [FE] LMS-78

src/app/core/components/admin/admin.interceptor.ts, src/app/core/services/auth/auth.service.ts
=> [FE] LMS-182

src/app/core/components/admin/admin.module.ts, src/app/core/components/admin/courses-page/courses-page.component.ts, src/app/core/components/admin/questions-page/all-question/all-question.component.html, src/app/core/components/admin/questions-page/all-question/all-question.component.scss, src/app/core/components/admin/questions-page/all-question/all-question.component.ts, src/app/core/components/admin/questions-page/edit-question/edit-question.component.html, src/app/core/components/admin/questions-page/edit-question/edit-question.component.ts, src/app/core/components/admin/questions-page/my-question/my-question.component.html, src/app/core/components/admin/questions-page/my-question/my-question.component.ts, src/app/core/components/admin/services/admin-questions.service.ts, src/app/core/components/admin/users-page/update-profile/update-profile.component.ts, src/app/core/components/admin/users-page/user-out/user-out.component.ts, src/app/core/components/questions/edit-question/edit-question.component.html, src/app/core/components/questions/edit-question/edit-question.component.ts, src/app/core/components/questions/my-questions/my-questions.component.html, src/app/core/components/questions/my-questions/my-questions.component.ts, src/app/core/components/questions/question.module.ts, src/app/core/components/user/edit-user/edit-user.component.ts, src/app/core/services/questions/questions.service.ts, src/app/shared/pipe/question.pipe.ts
Add possibility to edit question
=> [FE] LMS-67

src/app/core/components/admin/lessons-page/lesson-test/lesson-test.component.html, src/app/core/components/admin/lessons-page/lesson-test/lesson-test.component.ts, src/app/core/components/lessons/lesson-test/lesson-test.component.html
Testing on the subject (There was bad logic)
=> [FE] LMS-171

src/app/core/components/admin/admin.module.ts, src/app/core/components/admin/services/admin-users.service.ts, src/app/core/components/admin/users-page/create-user/create-user.component.html, src/app/core/components/admin/users-page/create-user/create-user.component.scss, src/app/core/components/admin/users-page/create-user/create-user.component.ts, src/app/core/components/admin/users-page/users-page.component.html, src/app/core/components/admin/users-page/users-page.component.ts, src/app/core/components/user/edit-user/edit-user.component.ts, src/app/shared/pipe/question.pipe.ts
Add functional to create user for admin
=> [FE][ADMIN] LMS-180

src/app/core/components/admin/admin-routing.module.ts, src/app/core/components/admin/admin.module.ts, src/app/core/components/admin/cities-admin/add-city-admin/add-city-admin.component.html, src/app/core/components/admin/cities-admin/add-city-admin/add-city-admin.component.ts, src/app/core/components/admin/cities-admin/cities-admin.component.html, src/app/core/components/admin/cities-admin/cities-admin.component.ts, src/app/core/components/admin/groups-page/create-group/create-group.component.html, src/app/core/components/admin/groups-page/create-group/create-group.component.ts, src/app/core/components/admin/interfaces/city.interface.ts, src/app/core/components/admin/interfaces/index.ts, src/app/core/components/admin/main-admin/main-admin.component.ts, src/app/core/components/admin/services/admin-city.service.ts
Create functional for create/get cities from DB
=> [FE][ADMIN] LMS-185

src/app/core/components/admin/interfaces/UserModel.ts, src/app/core/components/admin/interfaces/user-subject.model.ts, src/app/core/components/admin/interfaces/user.interface.ts, src/app/core/components/admin/users-page/create-user/create-user.component.html, src/app/core/components/admin/users-page/create-user/create-user.component.ts, src/app/core/components/admin/users-page/update-profile/update-profile.component.html, src/app/core/components/admin/users-page/update-profile/update-profile.component.ts, src/app/core/components/admin/users-page/user-out/user-out.component.html, src/app/core/components/admin/users-page/user-out/user-out.component.ts, src/app/core/components/admin/users-page/users-page.component.html, src/app/core/components/admin/users-page/users-page.component.ts, src/app/core/components/user/edit-user/edit-user.component.html, src/app/core/components/user/edit-user/edit-user.component.ts, src/app/core/components/user/registration/registration.component.html, src/app/core/components/user/registration/registration.component.ts, src/app/core/components/user/user-cabinet/user-cabinet.component.html, src/app/core/interface/UserModel.ts, src/app/core/interface/user-subject.model.ts
Add functional for user with city
=> [FE][ADMIN/MAIN] LMS-184

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/components/admin/cities-admin/cities-admin.component.ts, src/app/core/components/admin/groups-page/add-users/add-users.component.scss, src/app/core/components/admin/groups-page/add-users/add-users.component.ts, src/app/core/components/admin/resolvers/single-module.resolver.service.ts, src/app/core/components/groups/group-attendance/attendance.component.html, src/app/core/components/groups/group-attendance/attendance.component.scss, src/app/core/components/groups/group-attendance/attendance.component.ts, src/app/core/components/groups/groups.module.ts, src/app/core/components/groups/my-groups/my-groups.component.html, src/app/core/components/groups/my-groups/my-groups.component.scss, src/app/core/components/groups/my-groups/my-groups.component.ts, src/app/core/components/lessons/my-passed-test/my-passed-test.component.html, src/app/core/components/user/user.module.ts, src/app/core/resolvers/index.ts, src/app/core/resolvers/my-group.resolver.service.ts, src/app/core/resolvers/my-groups.resolver.service.ts, src/app/core/services/groups/groups.service.ts, src/app/shared/components/header/header.component.html
Get user groups on the user page
=> [FE][MAIN] LMS-187

src/app/core/components/lessons/my-passed-test/my-passed-test.component.html, src/app/core/components/lessons/my-passed-test/my-passed-test.component.ts, src/app/core/interface/test.interface.ts, src/app/core/services/user/user.service.ts
=> [FE][MAIN] LMS-190

src/app/core/components/admin/services/admin-questions.service.ts, src/app/core/components/admin/statistics-page/user/user.component.html, src/app/core/components/admin/statistics-page/user/user.component.ts, src/app/core/components/lessons/my-passed-test/my-passed-test.component.html, src/app/core/components/questions/questions-layout/questions-layout.component.html, src/app/core/components/questions/questions-layout/questions-layout.component.ts, src/app/core/interface/test.interface.ts, src/app/core/services/tests/test.service.ts
=> [FE][MAIN] LMS-197

src/app/core/components/admin/lessons-page/lesson-page/lesson-page.component.html, src/app/core/components/admin/lessons-page/lesson-page/lesson-page.component.ts, src/app/core/components/admin/services/admin-lesson.service.ts, src/app/core/components/lessons/lesson-page/lesson-page.component.html, src/app/core/components/lessons/lesson-page/lesson-page.component.ts, src/app/core/components/lessons/lesson-test/lesson-test.component.ts, src/app/core/services/lessons/lessons.service.ts
Add functional delete lesson and fix cascade deleting
=> [FE][MAIN] LMS-195

src/app/core/components/admin/admin.module.ts, src/app/core/components/admin/courses-page/courses-page.component.ts, src/app/core/components/admin/groups-page/add-users/add-users.component.ts, src/app/core/components/admin/module-page/add-lesson/add-lesson.component.html, src/app/core/components/admin/module-page/add-lesson/add-lesson.component.scss, src/app/core/components/admin/module-page/add-lesson/add-lesson.component.ts, src/app/core/components/admin/module-page/all-modules/all-modules.component.ts, src/app/core/components/admin/module-page/single-module/single-module.component.html, src/app/core/components/admin/module-page/single-module/single-module.component.ts, src/app/core/components/admin/services/admin-lesson.service.ts, src/app/core/components/admin/services/admin-module.service.ts
Add functional for delete and add lesson of module
=> [FE][ADMIN] LMS-196

src/app/core/components/admin/admin.module.ts, src/app/core/components/admin/interfaces/module.interface.ts, src/app/core/components/admin/module-page/edit-module/edit-module.component.ts, src/app/core/components/admin/module-page/single-module/single-module.component.ts, src/app/shared/components/header/header.component.html
=> [FE][MAIN] LMS-198

src/app/core/components/admin/module-page/add-lesson/add-lesson.component.ts, src/app/core/components/admin/questions-page/add-question/add-question.component.html, src/app/core/components/admin/questions-page/add-question/add-question.component.ts, src/app/core/components/admin/questions-page/edit-question/edit-question.component.html, src/app/core/components/admin/questions-page/edit-question/edit-question.component.ts, src/app/core/components/questions/add-question-form/add-question-form.component.html, src/app/core/components/questions/add-question-form/add-question-form.component.ts, src/app/core/components/questions/edit-question/edit-question.component.html, src/app/core/components/questions/edit-question/edit-question.component.ts, src/app/core/interface/questionModel.ts
=> [FE]LMS-204

src/app/core/components/admin/lessons-page/lesson-test/lesson-test.component.ts, src/app/core/components/admin/module-page/add-lesson/add-lesson.component.ts, src/app/core/components/admin/services/admin-test.service.ts, src/app/core/components/lessons/lesson-test-result/lesson-test-result.component.html, src/app/core/components/lessons/lesson-test/lesson-test.component.ts, src/app/core/components/lessons/my-passed-test/my-passed-test.component.html, src/app/core/components/lessons/my-passed-test/my-passed-test.component.ts, src/app/core/components/questions/questions-layout/questions-layout.component.ts, src/app/core/interface/test.interface.ts, src/app/core/services/tests/test.service.ts, src/app/core/services/user/user.service.ts
Create passed test schema and add functional for her
=> [FE] LMS-206

src/app/core/components/admin/admin-routing.module.ts, src/app/core/components/admin/admin.module.ts, src/app/core/components/admin/lessons-page/create-lesson-admin/create-lesson-admin.component.ts, src/app/core/components/admin/lessons-page/lesson-page/lesson-page.component.html, src/app/core/components/admin/lessons-page/lesson-page/lesson-page.component.ts, src/app/core/components/admin/module-page/add-lesson/add-lesson.component.html, src/app/core/components/admin/module-page/add-lesson/add-lesson.component.ts, src/app/core/components/admin/module-page/single-module/single-module.component.html, src/app/core/components/admin/questions-page/add-question/add-question.component.ts, src/app/core/components/admin/questions-page/questions-page.component.ts, src/app/core/components/admin/statistics-page/user/user.component.html, src/app/core/components/admin/users-page/create-user/create-user.component.html, src/app/core/components/admin/users-page/create-user/create-user.component.ts, src/app/core/components/admin/users-page/users-page.component.html, src/app/core/components/admin/users-page/users-page.component.ts, src/app/shared/components/templates/module-layout/module-layout.component.ts
=> [FE][ADMIN] LMS-207

src/app/core/components/admin/lessons-page/lesson-test/lesson-test.component.ts, src/app/core/components/admin/services/admin-test.service.ts, src/app/core/components/lessons/lesson-test/lesson-test.component.html, src/app/core/components/lessons/lesson-test/lesson-test.component.ts, src/app/core/interface/test.interface.ts, src/app/core/services/tests/test.service.ts
Fixed logic for count correct answers
=> [FE][MAIN] LMS-211

src/app/core/components/admin/interfaces/comment-interface.ts, src/app/core/components/admin/interfaces/index.ts, src/app/core/components/admin/lessons-page/edit-comment/edit-comment.component.html, src/app/core/components/admin/lessons-page/edit-comment/edit-comment.component.ts, src/app/core/components/admin/lessons-page/lesson-test/lesson-test.component.ts, src/app/core/components/admin/lessons-page/lesson.module.ts, src/app/core/components/admin/lessons-page/single-lesson/single-lesson.component.html, src/app/core/components/admin/lessons-page/single-lesson/single-lesson.component.ts, src/app/core/components/admin/services/admin-lesson.service.ts, src/app/core/components/admin/users-page/user-page/users-page.component.html, src/app/core/components/lessons/edit-comment/edit-comment.component.html, src/app/core/components/lessons/edit-comment/edit-comment.component.ts, src/app/core/components/lessons/lesson.module.ts, src/app/core/components/lessons/single-lesson/single-lesson.component.html, src/app/core/components/lessons/single-lesson/single-lesson.component.scss, src/app/core/components/lessons/single-lesson/single-lesson.component.ts, src/app/core/interface/comment-interface.ts, src/app/core/interface/index.ts, src/app/core/interface/lesson.interface.ts, src/app/core/services/lessons/lessons.service.ts
Create functional for commentaries
=> [FE] LMS-212

src/app/core/components/lessons/lesson-test/lesson-test.component.ts, src/app/core/components/questions/my-questions/my-questions.component.ts, src/app/core/components/tests/my-passed-test/my-passed-test.component.html, src/app/core/components/tests/my-passed-test/passed-question/passed-question.component.html, src/app/core/components/tests/my-passed-test/passed-question/passed-question.component.scss, src/app/core/components/tests/my-passed-test/passed-question/passed-question.component.ts, src/app/core/components/tests/tests.module.ts, src/app/core/interface/test.interface.ts
=> [FE] LMS-213

src/app/core/components/admin/lessons-page/create-lesson-admin/create-lesson-admin.component.html, src/app/core/components/admin/lessons-page/create-lesson-admin/create-lesson-admin.component.scss, src/app/core/components/admin/lessons-page/create-lesson-admin/create-lesson-admin.component.ts, src/app/core/components/admin/lessons-page/single-lesson/single-lesson.component.html, src/app/core/components/admin/lessons-page/single-lesson/single-lesson.component.scss, src/app/core/components/admin/lessons-page/single-lesson/single-lesson.component.ts, src/app/core/components/admin/services/admin-lesson.service.ts, src/app/core/components/lessons/create-lesson/create-lesson.component.html, src/app/core/components/lessons/create-lesson/create-lesson.component.scss, src/app/core/components/lessons/create-lesson/create-lesson.component.ts, src/app/core/components/lessons/lesson-test/lesson-test.component.html, src/app/core/components/lessons/lesson.module.ts, src/app/core/components/lessons/single-lesson/single-lesson.component.html, src/app/core/components/lessons/single-lesson/single-lesson.component.scss, src/app/core/components/lessons/single-lesson/single-lesson.component.ts, src/app/core/components/tests/questions-layout/questions-layout.component.html, src/app/core/services/auth/auth.service.ts, src/app/core/services/lessons/lessons.service.ts, src/app/core/services/user/user.service.ts, src/app/shared/components/header/header.component.ts
=> [FE] LMS-215

src/app/core/components/admin/services/admin-users.service.ts, src/app/core/components/admin/users-page/user-out/user-out.component.html, src/app/core/components/admin/users-page/user-out/user-out.component.scss, src/app/core/components/user/user-cabinet/user-cabinet.component.html, src/app/core/components/user/user-cabinet/user-cabinet.component.scss
Load users photo at Google Cloud
=> [FE] LMS-216

src/app/core/components/auth/auth-user/auth-user.component.html, src/app/core/components/auth/auth-user/auth-user.component.scss, src/app/core/components/auth/auth-user/auth-user.component.ts, src/app/core/components/auth/auth.module.ts, src/app/core/components/auth/form-email/form-email.component.html, src/app/core/components/auth/form-email/form-email.component.ts, src/app/core/components/auth/registration/registration.component.html, src/app/core/components/user/confirm-mail/confirm-mail.component.html, src/app/core/components/user/confirm-mail/confirm-mail.component.scss, src/app/core/components/user/confirm-mail/confirm-mail.component.ts, src/app/core/components/user/reset-password/reset-password.component.html, src/app/core/components/user/reset-password/reset-password.component.scss, src/app/core/components/user/reset-password/reset-password.component.ts, src/app/core/components/user/user-routing.module.ts, src/app/core/components/user/user.module.ts, src/app/core/services/auth/auth.service.ts, src/app/core/services/user/user.service.ts
Confirm email for registration and reset password
=> [FE] LMS-217

src/app/core/components/user/change-password/change-password.component.html, src/app/core/components/user/change-password/change-password.component.ts, src/app/core/components/user/confirm-mail/confirm-mail.component.html, src/app/core/components/user/confirm-mail/confirm-mail.component.ts, src/app/core/components/user/confirm-password/confirm-password.component.html, src/app/core/components/user/confirm-password/confirm-password.component.ts, src/app/core/components/user/edit-user/edit-user.component.html, src/app/core/components/user/edit-user/edit-user.component.ts, src/app/core/components/user/user-cabinet/user-cabinet.component.html, src/app/core/components/user/user-cabinet/user-cabinet.component.ts, src/app/core/components/user/user-routing.module.ts, src/app/core/components/user/user.module.ts, src/app/core/interface/UserModel.ts, src/app/core/services/user/user.service.ts
Change user password functional
=> [FE] LMS-218
